// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBB08oYeirg47u5emhZjWeNUMmOMxxog8',
    appId: '1:746538023958:android:f6fd647e17e289935a0937',
    messagingSenderId: '746538023958',
    projectId: 'all-in-one-socials',
    databaseURL: 'https://all-in-one-socials-default-rtdb.firebaseio.com',
    storageBucket: 'all-in-one-socials.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGV9dztaiawtcrRIvaRDZeplxYwwb3Dwk',
    appId: '1:746538023958:ios:b5161f7f30b36d805a0937',
    messagingSenderId: '746538023958',
    projectId: 'all-in-one-socials',
    databaseURL: 'https://all-in-one-socials-default-rtdb.firebaseio.com',
    storageBucket: 'all-in-one-socials.appspot.com',
    iosClientId: '746538023958-89q71nb08tbas3242259h70i69gr2q1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.allInOneSocials',
  );
}
